version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - postgres/postgresql.env #...
    volumes:
      - chatter-db:/var/lib/postgresql/data
    restart: on-failure

volumes:
  chatter-db:
